version: '3.8'

services:
  athenasordersapi:
    build:
      context: ../src
      dockerfile: Athenas.Orders.API/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrdersConnection=Host=db;Port=5432;Username=saga_user;Password=saga_pass;Database=AthenasOrders
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: AthenasOrders
      POSTGRES_USER: saga_user
      POSTGRES_PASSWORD: saga_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
